name: Bug report
description: Report a bug in CliqRex
title: "Bug: "
labels: ["bug", "triage"]
body:
  - type: checkboxes
    attributes:
      label: Avoid duplicates
      description: Please ensure you've completed the following
      options:
        - label: I have searched the [issues tracker](https://github.com/pixaura/cliqrex-main/issues) for a bug report similar to mine, in vain
          required: true
  # - type: input
  #   attributes:
  #     label: Ferdium Version
  #     description: What version of Ferdium are you using?
  #     placeholder: 6.0.0-nightly.7
  #   validations:
  #     required: true
  - type: dropdown
    attributes:
      label: What platform are you using?
      options:
        - iOS App
        - Android App
        - Web App
    validations:
      required: true
  - type: input
    attributes:
      label: Operating System Version
      placeholder: "e.g. Android Tiramasu, iOS 15.2"
    validations:
      required: true
  # - type: dropdown
  #   attributes:
  #     label: What arch are you using?
  #     options:
  #       - x64
  #       - ia32
  #       - arm64 (including Apple Silicon)
  #       - Other (specify in Additional information section)
  #   validations:
  #     required: true
  - type: input
    attributes:
      label: Last Known Working CliqRex version
      description: What is the last version of CliqRex this worked in, if applicable?
      placeholder: "0.0.18 (1810)"
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Behavior
      description: A clear description of what actually happens.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Explain to us how we can reproduce your bug on our device
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  # - type: input
  #   attributes:
  #     label: Debug link
  #     description: Please get your debug link via Ferdium's "Help" > "Publish Debug Information", then share your link with us
  #   validations:
  #     required: false
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help visualize your problem
  - type: textarea
    attributes:
      label: Additional information
      description: If your problem needs further explanation, please add more information here