name: Feature Request
description: Request a feature to be added
title: "[Request]: "
labels: ["new feature", "user-feedback", "triage"]
assignees:
  - palepinkdot
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: textarea
    id: what-is-your-idea
    attributes:
      label: What is your idea?
      description: Also give us all the details you can.
      placeholder: I think the app should give me free money!
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Which platform should we see this feature on?
      multiple: true
      options:
        - API
        - Mobile
        - Web
  - type: checkboxes
    id: contrib
    attributes:
      label: Make sure you have read the Contribution Guidelines.
      description: By submitting this issue, you agree to follow our [Contribution Guidelines](https://github.com/pixaura/cliqrex-main/blob/main/CONTRIBUTING.md)
      options:
        - label: I have read the Contribution Guidelines.
          required: true
  - type: textarea
    attributes:
      label: Additional information & file uploads